# Generated by Django 5.2.18 on 2026-10-08 16:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=254)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('driver_status', models.CharField(choices=[('none', 'Nežádá'), ('pending', 'Čeká na schválení'), ('approved', 'Schválen'), ('rejected', 'Zamítnut')], default='none', max_length=12)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('parental_consent_recorded', models.BooleanField(default=False)),
                ('parental_consent_note', models.CharField(blank=True, max_length=200)),
                ('pending_email', models.EmailField(blank=True, max_length=254)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('verify', 'Ověření'), ('change', 'Změna e-mailu')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ride', 'Nabízím jízdu'), ('demand', 'Hledám svezení')], max_length=10)),
                ('direction', models.CharField(choices=[('to', 'Do školy'), ('from', 'Ze školy')], max_length=10)),
                ('origin_area', models.CharField(max_length=120)),
                ('destination_area', models.CharField(max_length=120)),
                ('pickup_private', models.CharField(blank=True, max_length=200)),
                ('destination_private', models.CharField(blank=True, max_length=200)),
                ('origin_lat', models.FloatField(blank=True, null=True)),
                ('origin_lon', models.FloatField(blank=True, null=True)),
                ('destination_lat', models.FloatField(blank=True, null=True)),
                ('destination_lon', models.FloatField(blank=True, null=True)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('departure', models.DateTimeField()),
                ('flexibility_minutes', models.PositiveSmallIntegerField(default=0)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('conditions', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Aktivní'), ('resolved', 'Vyřešeno'), ('cancelled', 'Zrušeno'), ('completed', 'Dokončeno')], default='open', max_length=12)),
                ('route_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('route_duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(max_length=500)),
                ('link', models.CharField(default='/openride/', max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Otevřené'), ('closed', 'Uzavřené')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated_by', models.CharField(choices=[('passenger', 'Cestující'), ('driver', 'Řidič')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Čeká'), ('confirmed', 'Potvrzeno'), ('rejected', 'Odmítnuto'), ('cancelled', 'Zrušeno'), ('closed', 'Uzavřeno'), ('needs_reconfirm', 'Znovu potvrdit')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='app.listing')),
                ('ride', models.ForeignKey(limit_choices_to={'kind': 'ride'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='app.listing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'needs_reconfirm'])), fields=('ride', 'passenger'), name='one_active_booking_per_ride_passenger')],
            },
        ),
    ]
